spring:
  cloud:
    gateway:
      routes:
        - id: catalogo-route
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/categorias/**
        - id: catalogo-instancia
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/catalogo/instancia

        # PRODUCTO
        - id: producto-route
          uri: lb://producto
          predicates:
            - Path=/api/v1/productos/**
        - id: producto-instancia
          uri: lb://producto
          predicates:
            - Path=/api/v1/producto/instancia

        # INVENTARIO
        - id: inventario-route
          uri: lb://inventario
          predicates:
            - Path=/api/v1/inventario/**
        - id: inventario-instancia
          uri: lb://inventario
          predicates:
            - Path=/api/v1/inventario/instancia

        # CARRITO
        - id: carrito-route
          uri: lb://carrito
          predicates:
            - Path=/api/v1/carrito/**
        - id: carrito-instancia
          uri: lb://carrito
          predicates:
            - Path=/api/v1/carrito/instancia

        # ORDENES
        - id: ordenes-route
          uri: lb://ordenes
          predicates:
            - Path=/api/v1/ordenes/**
        - id: ordenes-instancia
          uri: lb://ordenes
          predicates:
            - Path=/api/v1/ordenes/instancia

        # PAGOS
        - id: pagos-route
          uri: lb://pagos
          predicates:
            - Path=/api/v1/pagos/**
        - id: pagos-instancia
          uri: lb://pagos
          predicates:
            - Path=/api/v1/pagos/instancia

eureka:
  client:
    service-url:
      defaultZone: http://registry-server:7081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"