CREATE TABLE IF NOT EXISTS inventarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_producto BIGINT NOT NULL,
    stock_disponible INT NOT NULL,
    stock_reservado INT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventarios_producto UNIQUE (id_producto),
    PRIMARY KEY (id)
);
