name: ecom-chat-ms-dev

services:
  postgres-chat-ms-dev:
    image: postgres:16-alpine
    container_name: ecom-postgres-chat-ms-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecom_chat_ms_db
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom
    ports:
      - "15444:5432"
    volumes:
      - ecom_chat_ms_dev_data:/var/lib/postgresql/data

volumes:
  ecom_chat_ms_dev_data:
