name: inventario-prod

services:
  mysql-inventario:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${INVENTARIO_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${INVENTARIO_MYSQL_DATABASE}
    ports:
      - "3432:3306" # Tu maquina (cliente externo) -> MySQL prod
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${INVENTARIO_MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - mysql_inventario_data:/var/lib/mysql
    networks:
      - inventario-int

  inventario:
    build: .
    restart: unless-stopped
    depends_on:
      mysql-inventario:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      INVENTARIO_DB_HOST: ${INVENTARIO_DB_HOST}
      INVENTARIO_DB_PORT: ${INVENTARIO_DB_PORT}
      INVENTARIO_DB_NAME: ${INVENTARIO_DB_NAME}
      INVENTARIO_DB_USERNAME: ${INVENTARIO_DB_USERNAME}
      INVENTARIO_DB_PASSWORD: ${INVENTARIO_DB_PASSWORD}
    ports:
      - "9132:9132"
    networks:
      - inventario-int
      - ms-net

volumes:
  mysql_inventario_data:

networks:
  ms-net:
    external: true
    name: ms-net
  inventario-int:
    name: inventario-int