name: pagos-dev

services:
  mysql-pagos-dev:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pagos
    ports:
      - "3421:3306" # Tu maquina (cliente externo) -> MySQL dev
    volumes:
      - mysql_pagos_dev_data:/var/lib/mysql

volumes:
  mysql_pagos_dev_data: