name: auth-dev

services:
  postgres-auth-dev:
    image: postgres:16-alpine
    container_name: postgres-auth-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom
    ports:
      - "15431:5432"
    volumes:
      - auth_dev_data:/var/lib/postgresql/data

volumes:
  auth_dev_data:
