name: ecom-inventario-dev

services:
  postgres-inventario-dev:
    image: postgres:16-alpine
    container_name: ecom-postgres-inventario-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecom_inventario_db
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom
    ports:
      - "15438:5432"
    volumes:
      - ecom_inventario_dev_data:/var/lib/postgresql/data

volumes:
  ecom_inventario_dev_data:
