CREATE TABLE IF NOT EXISTS carritos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_comprador BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(10,2) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_carritos_comprador ON carritos (id_comprador);
CREATE INDEX idx_carritos_producto ON carritos (id_producto);
