name: ecom-producto-dev

services:
  postgres-producto-dev:
    image: postgres:16-alpine
    container_name: ecom-postgres-producto-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecom_producto_db
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom
    ports:
      - "15433:5432"
    volumes:
      - ecom_producto_dev_data:/var/lib/postgresql/data

volumes:
  ecom_producto_dev_data:
