name: ordenes-prod

services:
  mysql-ordenes:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ORDENES_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ORDENES_MYSQL_DATABASE}
    ports:
      - "3412:3306" # Tu maquina (cliente externo) -> MySQL prod
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${ORDENES_MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - mysql_ordenes_data:/var/lib/mysql
    networks:
      - ordenes-int

  ordenes:
    build: .
    restart: unless-stopped
    depends_on:
      mysql-ordenes:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      ORDENES_DB_HOST: ${ORDENES_DB_HOST}
      ORDENES_DB_PORT: ${ORDENES_DB_PORT}
      ORDENES_DB_NAME: ${ORDENES_DB_NAME}
      ORDENES_DB_USERNAME: ${ORDENES_DB_USERNAME}
      ORDENES_DB_PASSWORD: ${ORDENES_DB_PASSWORD}
    ports:
      - "9112:9112"
    networks:
      - ordenes-int
      - ms-net

volumes:
  mysql_ordenes_data:

networks:
  ms-net:
    external: true
    name: ms-net
  ordenes-int:
    name: ordenes-int