name: ecom-kafka-dev

services:

  kafka:
    image: apache/kafka:4.2.0
    container_name: ecom-kafka-dev
    restart: unless-stopped
    ports:
      - "41092:41092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:41092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:41092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      ecom-dev-net:
        aliases:
          - kafka

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    container_name: ecom-kafka-exporter-dev
    restart: unless-stopped
    command:
      - --kafka.server=kafka:9092
    depends_on:
      - kafka
    ports:
      - "41308:9308"
    networks:
      ecom-dev-net:
        aliases:
          - kafka-exporter

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecom-kafka-ui-dev
    restart: unless-stopped
    ports:
      - "41085:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - ecom-dev-net

networks:
  ecom-dev-net:
    name: ecom-dev-net
