spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalogo-route
              uri: lb://catalogo
              predicates:
                - Path=/api/v1/categorias/**
            - id: catalogo-instancia
              uri: lb://catalogo
              predicates:
                - Path=/api/v1/catalogo/instancia
            - id: catalogo-swagger
              uri: lb://catalogo
              predicates:
                - Path=/catalogo/swagger-ui/**,/catalogo/v3/api-docs/**
            
            # PRODUCTO
            - id: producto-route
              uri: lb://producto
              predicates:
                - Path=/api/v1/productos/**
            - id: producto-instancia
              uri: lb://producto
              predicates:
                - Path=/api/v1/producto/instancia
            - id: producto-swagger
              uri: lb://producto
              predicates:
                - Path=/producto/swagger-ui/**,/producto/v3/api-docs/**
            
            # INVENTARIO
            - id: inventario-route
              uri: lb://inventario
              predicates:
                - Path=/api/v1/inventarios/**
            - id: inventario-instancia
              uri: lb://inventario
              predicates:
                - Path=/api/v1/inventarios/instancia
            - id: inventario-swagger
              uri: lb://inventario
              predicates:
                - Path=/inventarios/swagger-ui/**,/inventarios/v3/api-docs/**

            # CARRITO
            - id: carrito-route
              uri: lb://carrito
              predicates:
                - Path=/api/v1/carritos/**
            - id: carrito-instancia
              uri: lb://carrito
              predicates:
                - Path=/api/v1/carritos/instancia
            - id: carrito-swagger
              uri: lb://carrito
              predicates:
                - Path=/carritos/swagger-ui/**,/carritos/v3/api-docs/**

            # ORDENES
            - id: ordenes-route
              uri: lb://ordenes
              predicates:
                - Path=/api/v1/ordenes/**
            - id: ordenes-instancia
              uri: lb://ordenes
              predicates:
                - Path=/api/v1/ordenes/instancia
            - id: ordenes-swagger
              uri: lb://ordenes
              predicates:
                - Path=/ordenes/swagger-ui/**,/ordenes/v3/api-docs/**

            # PAGOS
            - id: pagos-route
              uri: lb://pagos
              predicates:
                - Path=/api/v1/pagos/**
            - id: pagos-instancia
              uri: lb://pagos
              predicates:
                - Path=/api/v1/pagos/instancia
            - id: pagos-swagger
              uri: lb://pagos
              predicates:
                - Path=/pagos/swagger-ui/**,/pagos/v3/api-docs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"