apiVersion: v1
kind: Secret
metadata:
  name: ecom-global-secret
  namespace: ecom
type: Opaque
stringData:
  jwt-secret: "1s3alJJATsWK91vf5zrODYlQa+LauM/9udaLZlQhHlpu46g/KzmSS5c3CGy6xF9kzAqBhvjmKBuZO/pSL7tfOg=="
  grafana-admin-user: "admin"
  grafana-admin-password: "grafana_secure_pass_2026"
