spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.ecom.svc.cluster.local:8080/realms/smartcampus
          jwk-set-uri: http://keycloak.ecom.svc.cluster.local:8080/realms/smartcampus/protocol/openid-connect/certs

keycloak:
  token-url: http://keycloak.ecom.svc.cluster.local:8080/realms/smartcampus/protocol/openid-connect/token
