spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: keycloak-route
          uri: ${KEYCLOAK_URL:http://keycloak:8080}
          predicates:
            - Path=/auth/**
        - id: catalogo-route
          uri: lb://catalogo-ms
          predicates:
            - Path=/api/v1/categorias/**
        - id: catalogo-instancia
          uri: lb://catalogo-ms
          predicates:
            - Path=/api/v1/catalogo/instancia
        - id: producto-route
          uri: lb://producto-ms
          predicates:
            - Path=/api/v1/productos/**
        - id: producto-instancia
          uri: lb://producto-ms
          predicates:
            - Path=/api/v1/producto/instancia
        - id: orden-route
          uri: lb://orden-ms
          predicates:
            - Path=/api/v1/ordenes/**
        - id: pago-route
          uri: lb://pago-ms
          predicates:
            - Path=/api/v1/pagos/**
        - id: carrito-route
          uri: lb://carrito-ms
          predicates:
            - Path=/api/v1/carritos/**
        - id: inventario-route
          uri: lb://inventario-ms
          predicates:
            - Path=/api/v1/inventarios/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: marketplace-client
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://keycloak:8080}/realms/smartcampus

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
