spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: auth-route
          uri: lb://AUTH-MS
          predicates:
            - Path=/auth/**
        - id: catalogo-route
          uri: lb://CATALOGO-MS
          predicates:
            - Path=/api/v1/categorias/**
        - id: catalogo-instancia
          uri: lb://CATALOGO-MS
          predicates:
            - Path=/api/v1/catalogo/instancia
        - id: producto-route
          uri: lb://PRODUCTO-MS
          predicates:
            - Path=/api/v1/productos/**
        - id: producto-instancia
          uri: lb://PRODUCTO-MS
          predicates:
            - Path=/api/v1/producto/instancia
        - id: orden-route
          uri: lb://ORDEN-MS
          predicates:
            - Path=/api/v1/ordenes/**
        - id: pago-route
          uri: lb://PAGO-MS
          predicates:
            - Path=/api/v1/pagos/**
        - id: carrito-route
          uri: lb://CARRITO-MS
          predicates:
            - Path=/api/v1/carritos/**
        - id: inventario-route
          uri: lb://INVENTARIO-MS
          predicates:
            - Path=/api/v1/inventarios/**
        - id: calificacion-route
          uri: lb://CALIFICACION-MS
          predicates:
            - Path=/api/v1/calificaciones/**
        - id: categoria-route
          uri: lb://CATEGORIA-MS
          predicates:
            - Path=/api/v1/categorias/**
        - id: chat-route
          uri: lb://CHAT-MS
          predicates:
            - Path=/api/v1/chats/**
        - id: favoritos-route
          uri: lb://FAVORITOS-MS
          predicates:
            - Path=/api/v1/favoritos/**
        - id: media-route
          uri: lb://MEDIA-MS
          predicates:
            - Path=/api/v1/media/**
        - id: notification-route
          uri: lb://NOTIFICATION-MS
          predicates:
            - Path=/api/v1/notificaciones/**
        - id: persona-route
          uri: lb://PERSONA-MS
          predicates:
            - Path=/api/v1/personas/**
        - id: publicacion-route
          uri: lb://PUBLICACION-MS
          predicates:
            - Path=/api/v1/publicaciones/**
        - id: search-route
          uri: lb://SEARCH-MS
          predicates:
            - Path=/api/v1/search/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: marketplace-client
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://keycloak:8080}/realms/smartcampus

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
