spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: auth-route
          uri: lb://auth-ms
          predicates:
            - Path=/auth/**
        - id: catalogo-route
          uri: lb://catalogo-ms
          predicates:
            - Path=/api/v1/categorias/**
        - id: catalogo-instancia
          uri: lb://catalogo-ms
          predicates:
            - Path=/api/v1/catalogo/instancia
        - id: catalogo-swagger
          uri: lb://catalogo-ms
          predicates:
            - Path=/catalogo-ms/swagger-ui/**,/catalogo-ms/v3/api-docs/**
        - id: producto-route
          uri: lb://producto-ms
          predicates:
            - Path=/api/v1/productos/**
        - id: producto-instancia
          uri: lb://producto-ms
          predicates:
            - Path=/api/v1/producto/instancia
        - id: producto-swagger
          uri: lb://producto-ms
          predicates:
            - Path=/producto-ms/swagger-ui/**,/producto-ms/v3/api-docs/**
        - id: orden-route
          uri: lb://orden-ms
          predicates:
            - Path=/api/v1/ordenes/**
        - id: orden-swagger
          uri: lb://orden-ms
          predicates:
            - Path=/orden-ms/swagger-ui/**,/orden-ms/v3/api-docs/**
        - id: pago-route
          uri: lb://pago-ms
          predicates:
            - Path=/api/v1/pagos/**
        - id: pago-swagger
          uri: lb://pago-ms
          predicates:
            - Path=/pago-ms/swagger-ui/**,/pago-ms/v3/api-docs/**
        - id: carrito-route
          uri: lb://carrito-ms
          predicates:
            - Path=/api/v1/carritos/**
        - id: carrito-swagger
          uri: lb://carrito-ms
          predicates:
            - Path=/carrito-ms/swagger-ui/**,/carrito-ms/v3/api-docs/**
        - id: inventario-route
          uri: lb://inventario-ms
          predicates:
            - Path=/api/v1/inventarios/**
        - id: inventario-swagger
          uri: lb://inventario-ms
          predicates:
            - Path=/inventario-ms/swagger-ui/**,/inventario-ms/v3/api-docs/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: marketplace-client
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/smartcampus

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${local.server.port:${server.port}}
    metadata-map:
      instance-port: ${local.server.port:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
