server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true

app:
  frontend-url: ${FRONTEND_URL}
  kafka:
    topic:
      ordenes: ordenes-topic
      pagos: pagos-topic
    group-id:
      pagos: pagos-group

mercadopago:
  access-token: ${MP_ACCESS_TOKEN}
  public-key: ${MP_PUBLIC_KEY:}
  base-url: https://api.mercadopago.com
  notification-url: ${MP_NOTIFICATION_URL}
  success-url: ${MP_SUCCESS_URL:${FRONTEND_URL}/pago/exito}
  failure-url: ${MP_FAILURE_URL:${FRONTEND_URL}/pago/fallo}
  pending-url: ${MP_PENDING_URL:${FRONTEND_URL}/pago/pendiente}
  auto-return-enabled: ${MP_AUTO_RETURN_ENABLED:true}

jwt:
  secret: 1s3alJJATsWK91vf5zrODYlQa+LauM/9udaLZlQhHlpu46g/KzmSS5c3CGy6xF9kzAqBhvjmKBuZO/pSL7tfOg==
  issuer: auth
