server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:41092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  datasource:
    url: jdbc:postgresql://localhost:15435/pago_db
    username: ecom
    password: ecom
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${local.server.port:${random.value}}
    metadata-map:
      instance-port: ${local.server.port:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}
  kafka:
    topic:
      ordenes: ordenes-topic
      pagos: pagos-topic
    group-id:
      pagos: pagos-group

mercadopago:
  access-token: ${MP_ACCESS_TOKEN}
  public-key: ${MP_PUBLIC_KEY:}
  base-url: https://api.mercadopago.com
  notification-url: ${MP_NOTIFICATION_URL:http://localhost:18080/api/v1/pagos/mercadopago/webhook}
  success-url: ${MP_SUCCESS_URL:${FRONTEND_URL:http://localhost:4200}/pago/exito}
  failure-url: ${MP_FAILURE_URL:${FRONTEND_URL:http://localhost:4200}/pago/fallo}
  pending-url: ${MP_PENDING_URL:${FRONTEND_URL:http://localhost:4200}/pago/pendiente}
  auto-return-enabled: ${MP_AUTO_RETURN_ENABLED:false}

jwt:
  secret: 1s3alJJATsWK91vf5zrODYlQa+LauM/9udaLZlQhHlpu46g/KzmSS5c3CGy6xF9kzAqBhvjmKBuZO/pSL7tfOg==
  issuer: auth
