name: ecom-pago-prod

services:
  postgres-pago:
    image: postgres:16-alpine
    container_name: ecom-postgres-pago
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - ecom_pago_data:/var/lib/postgresql/data
    ports:
      - "25435:5432"
    networks:
      - ecom-pago-int

  pago-ms:
    build: .
    container_name: ecom-pago-ms
    restart: unless-stopped
    depends_on:
      postgres-pago:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      DB_HOST: ecom-postgres-pago
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    expose:
      - "8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - ecom-pago-int
      - ecom-prod-net

volumes:
  ecom_pago_data:

networks:
  ecom-prod-net:
    external: true
    name: ecom-prod-net
  ecom-pago-int:
    name: ecom-pago-int
