ALTER TABLE IF EXISTS pagos
    ADD COLUMN IF NOT EXISTS id_vendedor BIGINT,
    ADD COLUMN IF NOT EXISTS publicacion_id BIGINT,
    ADD COLUMN IF NOT EXISTS titulo_producto VARCHAR(180),
    ADD COLUMN IF NOT EXISTS descripcion_producto VARCHAR(500),
    ADD COLUMN IF NOT EXISTS moneda VARCHAR(3) DEFAULT 'PEN';

UPDATE pagos
SET moneda = 'PEN'
WHERE moneda IS NULL;

ALTER TABLE IF EXISTS pagos
    ALTER COLUMN moneda SET NOT NULL;
